name: Publish

on:
  push:
    tags:
    # Must align with the tag-pattern configured on pub.dev.
    - 'url_strategy-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  pana:
    timeout-minutes: 9
    runs-on: ubuntu-latest
    name: Configuration of ${{ matrix.package }}
    strategy:
      matrix:
        package:
          - 'url_strategy'
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.3.3
      - uses: axel-op/dart-package-analyzer@v3
        with:
          relativePath: ${{ matrix.package }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: pana
    timeout-minutes: 4
    runs-on: ubuntu-latest
    name: Publishing of ${{ matrix.package }}
    strategy:
      matrix:
        package:
          - 'url_strategy'
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 2
          
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
        working-directory: ${{ matrix.package }}
      - run: flutter pub publish --dry-run
        working-directory: ${{ matrix.package }}
      - run: flutter pub publish --force
        working-directory: ${{ matrix.package }}
